[build-system]
requires = ["poetry-core>=1.5.0", "poetry-dynamic-versioning[plugin]>=1.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry]
name = "aquaduct"
description = "A project that includes the main package aquaduct and helper scripts in src/apps."
license = "GPL-3.0-or-later"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
homepage = "https://example.com/aquaduct"
repository = "https://github.com/yourusername/aquaduct"
packages = [{include = "aquaduct", from = "src"}]
version = "0.0.0"  # Required placeholder for poetry-dynamic-versioning
dynamic = ["version"]

[tool.poetry.dependencies]
python = ">=3.9"
MDAnalysis = "~2.9.0"
matplotlib = "~3.10.0"
numpy = "~2.2.0"
scipy = "~1.15.0"
packaging = "~24.0"
scikit-learn = "~1.6.0"
netCDF4 = "~1.7.0"

[tool.poetry.group.dev.dependencies]
build = "*"
coverage = "*"
sphinx = "*"
sphinxcontrib-aafig = "*"
poetry-dynamic-versioning = {extras = ["plugin"], version = "*"}

[tool.poetry.scripts]
valve = "aquaduct.scripts.valve:main"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
dirty = false
substitution.files = [
    "src/aquaduct/__init__.py",
]
# substitution.patterns = [
#     "(__version__ = )['\"]([^'\"]+)['\"]",
# ]
