[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aquaduct"
description = "A project that includes the main package aquaduct and helper scripts in src/apps."
license = { text = "GNU GPL v3" }
dynamic = ["version"]
dependencies = [
    "python>=3.9",
    "MDAnalysis~=2.9.0",
    "matplotlib~=3.10.0",
    "numpy~=2.2.0",
    "scipy~=1.15.0",
    "packaging~=24.0",
    "scikit-learn~=1.6.0",
    "netCDF4~=1.7.0"
]

[project.optional-dependencies]
dev = [
    # Add your development dependencies here
    # e.g., "pytest>=6.2.2"
    "build",
    "coverage"
]

[project.scripts]
valve = "aquaduct.scripts.valve:main"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"