#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

# Aqua-Duct, a tool facilitating analysis of the flow of solvent molecules in molecular dynamic simulations
# Copyright (C) 2016-2018 Michał Banas
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import ConfigParser
import argparse
import multiprocessing as mp
import sys
from collections import defaultdict
from time import time

import numpy as np
from aquaduct.traj.sandwich import Reader, Window, AtomSelection
from aquaduct.utils.multip import optimal_threads


class ReadMOL2(object):
    def __init__(self, mol2file):
        """
        Read mol2 files.

        Functionality is limited to fetching coordinates of atoms.
        Works only with files generated by WriteMOL2 class.

        :param mol2file: Filename.
        """
        self.file = open(mol2file, "r")

    def parse(self):
        """
        Parse MOL2 file.

        :return: Coordinates of atoms.
        """
        coords = []

        lines = [line.strip() for line in self.file.readlines()]

        i = 0
        while True:
            try:
                s = lines[i:].index("@<TRIPOS>ATOM") + 1 + i
                e = lines[i:].index("@<TRIPOS>BOND") + i
            except ValueError:
                break

            coords.append([np.array((line.split()[2], line.split()[3], line.split()[4]), dtype=np.float32)
                           for line in lines[s:e]])

            i = e + 1

        return np.array(coords)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.__del__()

    def __del__(self):
        self.file.close()


class Worker(object):
    def __init__(self, hotspots_coords, atoms_coords):
        self.hotspots_coords = hotspots_coords
        self.atoms_coords = atoms_coords

    def __call__(self, hotspot_id):
        in_area = []
        for id_, coord in self.atoms_coords:
            if float(np.linalg.norm(coord - self.hotspots_coords[hotspot_id])) <= float(args.distance):
                in_area.append(id_)

        return hotspot_id, in_area


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("config_file", help="Config filename.")
    parser.add_argument("hotspots_file", help="Hotspots filename.")
    parser.add_argument("-d", dest="distance", required=True, help="Distance from hotspots.")
    parser.add_argument("-t", dest="threads", required=False, default=None, help="Number of threads.")
    parser.add_argument("-m", dest="maxaa", required=False, default=None,
                        help="Maximum number of returned AA per hotspot.", type=int)

    args = parser.parse_args()

    config = ConfigParser.RawConfigParser()
    config.readfp(open(args.config_file, "r"))

    top_file = config.get("global", "top")
    trj_files = config.get("global", "trj")

    with ReadMOL2(args.hotspots_file) as hotspots_file:
        line = hotspots_file.readline()
        if line.startswith("# Windows:"):
            windows_t = line.rstrip("# Windows:").split(" ")
            windows = []
            for window in windows_t:
                windows.append((int(w) for w in window.rstrip("(").lstrip(")").split(",")))
        else:
            raise RuntimeError("Windows information missing.")

        hotspots_coords = hotspots_file.parse()[0]  # TODO: Remove it for window calculations

    if args.threads is None:
        optimal_threads.threads_count = optimal_threads.cpu_count + 1
    else:
        optimal_threads.threads_count = int(args.threads)

    Reader(top_file, trj_files, window=Window(args.minf, args.maxf, args.stepf), threads=optimal_threads.threads_count)

    print "Threads used: {}".format(optimal_threads.threads_count)
    print "Frame range: {}-{} Step: {}".format(Reader.window.start, Reader.window.stop, Reader.window.step)
    print "Distance from hotspot: {}".format(args.distance)

    print "Windows:"
    for window in windows:
        print "{}:{}".format(window[0], window[1])

    residue_occurences = defaultdict(dict)

    stime = time()

    print "\nFinding the hottest place in the universe:"
    pool = mp.Pool(processes=optimal_threads.threads_count)

    for window in windows:
        for traj_reader in Reader.iterate():
            traj_reader = traj_reader.open()

            protein_atoms = traj_reader.parse_selection("protein")

            for frame in range(window[0], window[1]+1):
                traj_reader.set_frame(frame)
                in_area = defaultdict(dict)
                for number, ids in protein_atoms.selected.iteritems():
                    number_reader = protein_atoms.get_reader(number)

                    atoms_coords = zip(ids, number_reader.atoms_positions(ids))
                    worker = Worker(hotspots_coords, atoms_coords)

                    results = pool.map(worker, range(0, len(hotspots_coords)))

                    for hotspot_id, atoms_ids in results:
                        if number not in in_area[hotspot_id]:
                            in_area[hotspot_id][number] = list()

                        in_area[hotspot_id][number].extend(atoms_ids)

                in_area_selections = {}
                for hotspot_id, selection in in_area.iteritems():
                    in_area_selections[hotspot_id] = AtomSelection(selection)

                for hotspot_id, hotspot_atom_selection in in_area_selections.iteritems():
                    for id_, name in zip(hotspot_atom_selection.residues().ids(),
                                         hotspot_atom_selection.residues().names()):
                        if (id_[1], name) not in residue_occurences[hotspot_id]:
                            residue_occurences[hotspot_id][(id_[1], name)] = 0

                        residue_occurences[hotspot_id][(id_[1], name)] += 1

        print
        print "* Window: {}:{}".format(window[0], window[1])
        window_len = window[1] - window[0]
        for hotspot_id, hotspot_occurences in residue_occurences.iteritems():
            print "-" * 20
            print hotspot_id, hotspots_coords[hotspot_id]
            print "-" * 20
            for i, res in enumerate(sorted(hotspot_occurences, key=hotspot_occurences.get, reverse=True)):
                if i == args.maxaa:
                    break

                proc = round(hotspot_occurences[res] / window_len, 2) * 100
                if proc < 1.:
                    proc = float(("{0:.%ie}" % 1).format(proc))
                print "{:<7} | {:5} | {:3} | {}%".format(i, res[0] + 1, res[1],
                                                         round(hotspot_occurences[res] / window_len, 2) * 100)

    sys.stdout.write("\r {:.2} s".format(time() - stime))
