#!/usr/bin/env python2.7
import argparse
import time

import ConfigParser
import numpy as np
import sys

from aquaduct.traj.sandwich import Window, Reader
from aquaduct.utils.multip import optimal_threads


class ReadMOL2(object):
    def __init__(self, mol2file):
        """
        Read mol2 files.

        Functionality is limited to fetching coordinates of atoms.
        Works only with files generated by WriteMOL2 class.

        :param mol2file: Filename.
        """
        self.file = open(mol2file, "r")

    def parse(self):
        """
        Parse file.

        :return: Coordinates of atoms.
        """
        lines = [line.strip() for line in self.file.readlines()]
        header_index = lines.index("@<TRIPOS>ATOM")

        coords = []
        for data in lines[header_index + 1:]:
            if data == "@<TRIPOS>BOND":
                break

            x, y, z = data.split()[2:5]
            coords.append([x, y, z])

        return np.asarray(coords, dtype=np.float32)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.__del__()

    def __del__(self):
        self.file.close()

if __name__ == "__main__":
    # a = np.array([1, 2, 3, 4, 5])
    # print(a[[4, 5]])
    # sys.exit(0)
    np.set_printoptions(threshold=sys.maxsize)

    parser = argparse.ArgumentParser()
    parser.add_argument("config_file", help="Config filename.")
    parser.add_argument("hotspots_file", help="Hotspots filename.")
    parser.add_argument("-d", dest="distance", required=True, help="Distance from hotspots.")
    parser.add_argument("-t", dest="threads", required=False, default=None, help="Number of threads.")
    parser.add_argument("-m", dest="maxaa", required=False, default=None,
                        help="Maximum number of returned AA per hotspot.", type=int)
    parser.add_argument("-s", dest="minf", required=False, default=None,
                        help="Start frame.")
    parser.add_argument("-e", dest="maxf", required=False, default=None,
                        help="End frame.")
    parser.add_argument("-st", dest="stepf", required=False, default=None,
                        help="Frame step.")

    args = parser.parse_args()

    config = ConfigParser.RawConfigParser()
    config.readfp(open(args.config_file, "r"))

    top_file = config.get("global", "top")
    trj_files = config.get("global", "trj")
    distance = float(args.distance)

    with ReadMOL2(args.hotspots_file) as hotspots_file:
        hotspots_coords = hotspots_file.parse()

    if args.threads is None:
        optimal_threads.threads_count = optimal_threads.cpu_count + 1
    else:
        optimal_threads.threads_count = int(args.threads)

    print
    "Threads used: {}".format(optimal_threads.threads_count)

    Reader(top_file, trj_files, window=Window(args.minf, args.maxf, args.stepf), threads=optimal_threads.threads_count)

    print
    "Frame range: {}-{} Step: {}".format(Reader.window.start, Reader.window.stop, Reader.window.step)
    print
    "Distance from hotspot: {}".format(args.distance)

    is_initialized = False
    selected_atoms_ids = None
    selected_residues_ids = None
    atoms_residues = None
    hotspot_atoms_occurences = None
    hotspot_residues_occurences = None

    start_time = time.time()
    for traj_reader in Reader.iterate():
        traj_reader = traj_reader.open()
        traj = traj_reader.trajectory_object

        if not is_initialized:
            selected_atoms_ids = traj.select_atoms("protein")
            selected_residues_ids = selected_atoms_ids.residues
            hotspot_atoms_occurences = np.zeros((len(hotspots_coords), len(selected_atoms_ids)), dtype=int)
            hotspot_residues_occurences = np.zeros((len(hotspots_coords), len(selected_residues_ids)), dtype=int)
            is_initialized = True

        for _ in traj_reader.iterate():
            sys.stdout.write("\rExecution time: {:.2f}".format(time.time() - start_time))
            for i, hotspot_coord in enumerate(hotspots_coords):
                atoms_positions = traj_reader.atoms_positions(selected_atoms_ids.ix)
                atoms_distances_from_hotspot = np.linalg.norm(atoms_positions - hotspot_coord, axis=1)
                hotspot_atoms_occurences[i][atoms_distances_from_hotspot <= distance] += 1
                residues_occurenced = selected_atoms_ids[atoms_distances_from_hotspot <= distance].residues
                residues_occurenced_indexes = np.searchsorted(selected_residues_ids, residues_occurenced)

                # FIXME: Find way to do this using pure numpy
                for ii in residues_occurenced_indexes:
                    hotspot_residues_occurences[i][ii] += 1

    print "\n"
    for hotspot_id in range(len(hotspots_coords)):
        all_atoms_occurences = hotspot_atoms_occurences[hotspot_id]
        all_residues_occurences = hotspot_residues_occurences[hotspot_id]
        residues_indices = all_residues_occurences > 0
        residues_occurences = all_residues_occurences[residues_indices]
        residues = selected_residues_ids[residues_indices]

        if not residues:
            continue

        print "Hotspot {} {}".format(hotspot_id, hotspots_coords[hotspot_id])

        for res, occ in zip(residues, residues_occurences):
            print "\t{} {} {:.2f}%".format(res.ix, res.resname, occ*1.0/Reader.window.len() * 100)
            for atom_index in np.searchsorted(selected_atoms_ids.ix, res.atoms.ix):
                o = all_atoms_occurences[atom_index]*1.0/Reader.window.len() * 100
                if (0 > atom_index >= len(selected_atoms_ids)) or not o:
                    continue
                print "\t\t{} {} {:.2f}%".format(selected_atoms_ids[atom_index].ix,
                                            selected_atoms_ids[atom_index].type,
                                            o)
        print("-"*50)
